---
- name: Traefik Namespace の作成
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ traefik_namespace }}"

- name: Traefik Helm リポジトリの登録
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://traefik.github.io/charts"
    state: present

- name: Traefik のインストール
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: "{{ traefik_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    values:
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      ingressClass:
        enabled: true
        isDefaultClass: true
