---
- name: master の初期化と CNI 適用
  hosts: master
  become: true
  roles:
    - role: kubeadm_init
      tags: [kubeadm, init]
    - role: cni_calico
      tags: [cni, calico]
    - role: k8s_python
      tags: [python]
